### ISSUE TITLE
Poor Scaling In Matmul and Exp Demos

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ut-parla/Parla.py#15]
This is likely some kind of performance bug. Both the matmul and exp demo are really simple cases where parla ought to perform much better than it currently does. Right now both apps show near ideal scaling up to two devices and then plateau after that.

**Comment by insertinterestingnamehere** [comment]
Current data for exp (On Tuxedo, using only the k80s)
1gpu: 0.64 s
2gpu: 0.3 s
4gpu: 0.67 s

These times are small enough that poor scaling after a point is reasonable.

**Comment by insertinterestingnamehere** [comment]
Current data for matmul (same machine)
1gpu: 6.98 s
2gpu: 3.52 s
4gpu: 3.83 s

**Comment by insertinterestingnamehere** [comment]
In the exp app case the poor scaling appears to be because in the 4 GPU case, one of the GPUs consistently takes the full time to finish its portion of the workload. Which one varies (though I think it's usually the first on on either socket). The tasks all launch within the first 4ms though, so it seems unlikely that there's an issue inside the scheduler.

**Comment by insertinterestingnamehere** [comment]
In the 2 device case there's no visible performance difference between GPUs. Maybe this is NUMA?

**Comment by insertinterestingnamehere** [comment]
Weak scaling for exp is also only okay.
1gpu: .64s
2gpu: .56s
4gpu: 1.22s

**Comment by insertinterestingnamehere** [comment]
In one run of the largest case (weak scaling experiment at 4 gpus), one GPU completes in .2s, one in .54, one in 1.12, and two more in 1.13.

**Comment by insertinterestingnamehere** [comment]
In that largest experiment I'm also seeing a lot of variation in the running times. Another run shows times .36, .52, .68, and .85 and ends the whole run in .95s. The devices finish in order 0, 1, 2, 3 in the first case and 0, 2, 1, 3 in the second.

**Comment by insertinterestingnamehere** [comment]
The variation goes away after multiple runs. I made the mistake of timing the first run of that size, so that's why it was so bad. The second run is more representative.

**Comment by insertinterestingnamehere** [comment]
Nevermind, additional runs are showing more unpredictable behavior. I just had three of them finish in around .75s, so near ideal weak scaling. This seems consistent now that the devices are warmed up. Given that, can we just write this off as the problem size not being costly enough to show good strong scaling?

**Comment by insertinterestingnamehere** [comment]
I'm not sure why several warmup runs help in this case though.

**Comment by arthurp** [comment]
Cupy maintains caches of various CUDA objects. That might cause a warmup effect.

**Comment by insertinterestingnamehere** [comment]
Across different processes though?

**Comment by arthurp** [comment]
.... Oh. That's weird. I thought you meant warming up in one process.

**Comment by insertinterestingnamehere** [comment]
Yah, it's a new process each run. Maybe the boost frequency is responding slowly?

**Comment by insertinterestingnamehere** [comment]
I just ran a whole bunch of single GPU runs in a bash loop. The time remains steady so it looks like the warmup effect doesn't apply in that case.

**Comment by insertinterestingnamehere** [comment]
No warm up effect with two GPUs either.

**Comment by insertinterestingnamehere** [comment]
matmul strong scaling:
1gpu: 6s - 7s (first run)
2gpu: 3.5s - 3.56s
4gpu: 3.2s - 4.8s

So, lots of variation in the 4gpu times. No burn-in, just a ton of variation. I'll check the larger problem size.

**Comment by insertinterestingnamehere** [comment]
@arthurp just to confirm, do we ever clean up our worker threads? I'm trying to look at this with mtprof and it's choking because a bunch of threads are still running.

**Comment by arthurp** [comment]
~~All the threads (the scheduler and all workers) should be joined in `Scheduler.__exit__`. This should be called at the end of `with Parla():`. I don't see any issues with the code in a quick reading, but it could be missing something. I think the scheduler should create one thread per device by default, which would be at most one per core and one per GPU.~~

I just realized the issue. I'm waiting for all the threads to complete, but I'm *not* joining them. So you may be seeing zombie threads. I think you need to add a loop to join all the workers and join the scheduler thread just before: https://github.com/ut-parla/Parla.py/blob/6c866dc9de0912de5227467f2b25b57551b41fb9/parla/task_runtime.py#L669

**Comment by insertinterestingnamehere** [comment]
Got it. Thanks for pointing to where that should go.

**Comment by insertinterestingnamehere** [comment]
Okay, the zombies are slain. Thanks!

**Comment by insertinterestingnamehere** [comment]
Note about matmul: switching to columnar layout within the block of rows sent to each device actually makes the problem worse. I have no idea why since it seems like that ought to help communication overheads since communicated blocks become contiguous.

**Comment by insertinterestingnamehere** [comment]
On the other hand, magma doesn't actually include a multi-GPU matrix-matrix multiplication routine, so maybe this is a known issue with matrix multiplication? That'd be bizarre, but not totally impossible.

**Comment by insertinterestingnamehere** [comment]
Actually here's why Magma doesn't support it: http://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=1638#p4546. Apparently it's really easy to do yourself, which doesn't help explain why we have this performance bug on such a basic problem.

**Comment by insertinterestingnamehere** [comment]
Probably the next thing to try is decreasing the block size. Maybe the poor performance is coming from contention for communication bandwidth. Decreasing the block size will (hopefully) overlap the computation and communication better to mitigate that somewhat.

**Comment by dialecticDolt** [comment]
I'm fairly certain what we're seeing here is that CuBLAS initialization is per thread (and partially serialized in the runtime). If we warmup the code by running the threaded version multiple times this behavior vanishes. 

Note that warming up on the main thread does not effect this (for example in the matmul_futures example).  
I'm not sure this makes sense though, shouldn't the new TheadPoolExecutor and CuPy not have an persistent data between the new and old thread pools?

**Comment by insertinterestingnamehere** [comment]
Weird. Okay. Maybe there's some caching going on at some level? Either way, I think we can add a hook to initialize/warm up stuff like this for all our worker threads in advance.

**Comment by insertinterestingnamehere** [comment]
Note: this is supposed to be fixed in https://github.com/ut-parla/Parla.py/pull/20. Some of the issues are still lingering though. For the time being, the fix is likely to be just running each benchmark a few times *in the same process* before collecting numbers. I need to run some more tests to confirm that that's the case. If so, that should at least clear this for the paper milestone. Ideally we'll have something more clear-cut in the long-term.

**Comment by insertinterestingnamehere** [comment]
Okay, I've confirmed that this is still hitting those apps. Here's a wild new theory. I know CUDA JIT compiles kernels to device-specific bytecode. This overhead would totally be explained if that compilation process happens at the CPU level, is not thread safe, and runs once per device regardless of whether or not devices are the same model. @arthurp @dialecticDolt @burtscher  what do you think?

**Comment by dialecticDolt** [comment]
You mean it's still hitting with the per thread warmup hooks?

**Comment by arthurp** [comment]
Let's just run a full warm up rep of every benchmark instead of fighting this. None of the benchmarks are so long that an extra rep would be a huge problem. The warm up rep will just eliminate any chance off these issues. (By warm up rep, I mean run the whole benchmark once in a process, then run the number of reps you would usually run like 5 and then exit.)

**Comment by insertinterestingnamehere** [comment]
Yep. It's still hitting per-thread warmups.

**Comment by burtscher** [comment]
To be on the safe side, you could write a trivial kernel and launch it on each GPU as part of the startup/initialization of Parla. Maybe do this from a single thread and copy the (useless) results back. That should take care of all the JITing for all GPUs (as far as I know, everything is JITed together, it's not kernel by kernel).

**Comment by insertinterestingnamehere** [comment]
Yah, I agree that the solution is per-thread warmups for the time being. I just confirmed that that eliminates the problem for the exp demo. Still need to confirm for matmul.

**Comment by insertinterestingnamehere** [comment]
@burtscher Thanks, that's a great suggestion. I was thinking it was per-kernel. That's totally doable.

**Comment by insertinterestingnamehere** [comment]
I'll try it and report back...

**Comment by insertinterestingnamehere** [comment]
Weird. Okay. That mostly fixed it for device 0 and did nothing for device 1. I'll go double-check that we're actually running the init step on every thread.

**Comment by insertinterestingnamehere** [comment]
Okay, that looks fine. I'm not sure what's happening. I'll push what I have. For this deadline let's just do a warmup run. I'll leave this issue open but clear it from the milestone.

**Comment by insertinterestingnamehere** [comment]
I messed with this a bit more this morning and wasn't able to pin down what's left. Currently the exp demo still shows warmup behavior from some kind of hidden initialization. Somehow only one thread is showing the warmup overhead now even though they all run the same setup code. The matmul demo is still only scaling to two devices, I think it's communication overhead from data transfer across NUMA domains, but it'd be nice to be sure.

**Comment by insertinterestingnamehere** [comment]
Idk if we're going to follow up on this specific issue further in the near-term future. Closing.
