### ISSUE TITLE
Buggy Cross-GPU Synchronization?

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ut-parla/Parla.py#17]
Currently the cholesky app shows some nondeterministic errors. Our current theory is that there's some kind of issue with the way we map tasks onto streams in the multi-device setting.

**Comment by insertinterestingnamehere** [comment]
Current best guess for a fix: replacing the stream synchronize at the end of each task with a cuda event at the end of each task.

**Comment by insertinterestingnamehere** [comment]
Copied question from slack for @burtscher: Martin, any chance you could clarify any differences between stream.synchronize and cuda events for cross-device coordination? We're seeing some synchronization bug of some kind. Hochan has more details, but we're suspecting something is wrong with the way we synchronize the cuda streams that tasks run on. Right now we call cudaStreamSynchronize (through a wrapper) at the end of each task to guarantee that the output data will be ready to use/copy for any dependent tasks that run after the task has completed even if those tasks are running on another GPU. Is it possible that a stale read could still occur if a dependent task on a different device copies the output data from a task after the stream has been synchronized? We're considering switching over to using cuda events to prevent issues like this. Would there be any functional difference with using cuda events?

**Comment by insertinterestingnamehere** [comment]
Also worth noting from the slack discussion: @arthurp pointed out that Python-level interfaces for the cuda event apis are available. See https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.Stream.html#cupy.cuda.Stream.record and https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.Stream.html#cupy.cuda.Stream.wait_event.

**Comment by burtscher** [comment]
Hi Ian,

I only have limited experience with multi-GPU code and never faced this issue before, so I don't know. Sorry.

The documentation says "cudaStreamWaitEvent() can therefore be used to synchronize multiple devices with each other."

Also, maybe "__threadfence_system()" will help.

Have a great day,
Martin

**Comment by insertinterestingnamehere** [comment]
Thanks Martin. That's helpful. The fact that the events api documentation explicitly mentions cross-device synchronization while the stream synchronize api documentation does not is one reason why we suspect that this is what's going on.

**Comment by insertinterestingnamehere** [comment]
@nicelhc13 has identified the issue as coming because cupy.asarray operates on the default stream regardless of the current stream. I've submitted an issue about this upstream in https://github.com/cupy/cupy/issues/4988.

**Comment by insertinterestingnamehere** [comment]
Okay, we have a temporary workaround for this merged in https://github.com/ut-parla/Parla.py/pull/21. I'm clearing this from the paper milestone but leaving it open because it needs more follow-up after a fix is applied upstream.

**Comment by insertinterestingnamehere** [comment]
This has been fixed upstream in https://github.com/cupy/cupy/pull/5004. Once that's available in their binaries we can just check for a recent enough CuPy and get rid of our workarounds.

**Comment by arthurp** [comment]
I think this is fixed. @insertinterestingnamehere is this fully resolved?

**Comment by insertinterestingnamehere** [comment]
Yep. This is fixed in cupy version 9.0 and later.
