### ISSUE TITLE
Handling resource assignment failure

### ISSUE THREAD

**Issue by bozhiyou** [ut-parla/Parla.py#38]
https://github.com/ut-parla/Parla.py/blob/master/parla/task_runtime.py#L790-L795
It warns when the assignment fails too many times: `Failed to assign devices. The required resources may not be available on this machine at all.` However, cases can be that tasks are competing for a particular device, e.g. many tasks wanting a particular GPU. The failure should be warned with more details and there may be another way to handle the competing case.

**Comment by arthurp** [comment]
Duplicates #29
