### ISSUE TITLE
Allocating Numpy Arrays in Pinned Host Memory

### ISSUE THREAD

**Issue by insertinterestingnamehere** [ut-parla/Parla.py#42]
This probably needs to be addressed upstream, but it affects our apps like QR and Barnes Hut that use the pattern of copy to GPU, compute, send the data back in each task. I'm documenting it now and we can try discussing upstream later. We'd like to allow host-to-device and device-to-host transfers to happen fully asynchronously, but cuda can only do that for memory with pinned pages. It looks like someone has already worked around this to some extent in the chainer source code. We should follow that example. See https://stackoverflow.com/a/47492027.

**Comment by leofang** [comment]
This will be enabled by https://github.com/cupy/cupy/pull/4870.

**Comment by insertinterestingnamehere** [comment]
Thanks! That is super helpful!

**Comment by arthurp** [comment]
Closing as this is merged upstream, and we don't need to fix it.

**Comment by insertinterestingnamehere** [comment]
Yep. This is also available in cupy 9.0.
