### ISSUE TITLE
Persistent memory location

### ISSUE THREAD

**Issue by nicelhc13** [ut-parla/Parla.py#47]
I am not sure if I am using persistent memory parameter properly, but my code doesn't work as I expected.

This is parts of the multiGPU blocked cholesky code and usage of the persistent memory parameter: [here](https://gist.github.com/nicelhc13/8b800fd135ae9cdce1ff50b8337310aa#file-gistfile1-txt-L60)

I would like to pre-define/allocate persistent memory for each device before starting the loop.

[This](https://gist.github.com/nicelhc13/8b800fd135ae9cdce1ff50b8337310aa#file-gistfile1-txt-L158) call allocates and append memory for each GPU to the `gpu_arrs`. Therefore, the first dimension of the `gpu_arrs` is memory for each gpu (like gpu_arrs[0] -> gpu0, gpu_arrs[1] -> gpu1, ..)

Then, I pass `gpu_arrs` to the `reserve_persistent_memory()`.

My expectation is each gpu is aware of data owned by them.
(e.g. gpu0 knows gpu_arrs[0].nbytes are residing on its memory)

But, Parla allocates all memory to the current device. 
For example, my usecase allocates all memory on the gpu0.
This is because `reserve_persistent_memory()` makes reference or copies the source data first
and then uses device information of its newly created/referenced array.
[Link](https://github.com/ut-parla/Parla.py/blob/ce1a4d3e284a7bee83dd44a98a9f205d56f317ed/parla/tasks.py#L512)

Therefore, it degraded performance.

For tests, my temporary solution is to replace `view.device` with `amount.device`.

I was wondering if it is right usecase.

**Comment by insertinterestingnamehere** [comment]
Yep. This makes sense. Thanks for finding it. I'll push a patch.

**Comment by insertinterestingnamehere** [comment]
For some reason my expectation had been that cupy would leave the array on the device if it was making a view via the `__cuda_array_interface__` protocol. In retrospect though, that makes no sense. We'll have to use some other kind of routine to make it do that.

**Comment by insertinterestingnamehere** [comment]
For now I'll just make it work for cupy arrays.

**Comment by nicelhc13** [comment]
Thank you very much

**Comment by arthurp** [comment]
>  We'll have to use some other kind of routine to make it do that.

I'm pretty sure [`parla.array.get_memory()`](https://github.com/ut-parla/Parla.py/blob/master/parla/array.py#L84) handles this correctly already, and [`parla.array.storage_size()`](https://github.com/ut-parla/Parla.py/blob/master/parla/array.py#L135) can be improved to handle it correctly by pushing the storage size operation into the [`ArrayType`](https://github.com/ut-parla/Parla.py/blob/master/parla/array.py#L17) abstraction.

Overall, I think allowing registration of new data/array types is very important since it will enable arbitrary external libraries to be used with Parla without direct support for Parla and without needing to make the external library numpy compatible.

**Comment by insertinterestingnamehere** [comment]
Yes, though everything array-like in the Python ecosystem conforms to either pep 3118, `__array_interface__`, or `__cuda_array_interface__`. We don't even need to register types if we rely on those standards.

**Comment by insertinterestingnamehere** [comment]
I guess the one exception to that would be obscure numpy types that aren't actually in PEP 3118, or other array-like objects that are working toward more generalized layouts that just don't always fit inside the existing standard (e.g. taco and DyND). In DyND we supported the PEP 3118 interface, but it couldn't actually encapsulate all the types we could.

**Comment by arthurp** [comment]
Yes, those to cases will cover a lot (though not everything as you say). I think the `__array_interface__` and `__cuda_array_interface__` support should also be registered `ArrayTypes`. No reason to special case one interface and not another, and it avoids the temptation to import extra modules in places they are not always needed. I wrote array types for `numpy` and `cupy` and as you point out writting array types for those abstract `__` interfaces would be better.
